### ISSUE TITLE
[SPEC] Migration of notebook extension definitions to jupyter_server

### ISSUE THREAD

**Issue by echarles** [jupyterlab/nbclassic#6]
This is a place to finalize the discussion related to the migration of the extension files from https://github.com/jupyter/notebook to https://github.com/jupyter/jupyter_server.

**Goal**

Collect the json files located in `jupyter_paths` which contain a `NotebookApp` stanza, e.g. `jupyterlab_git.json` looking like:

```json
{
    "NotebookApp": {
      "nbserver_extensions": {
            "jupyterlab_git": true
      }
    }
  }
```

Convert the collected files to something like:

```json
{
    "ServerApp": {
      "nbserver_extensions": {
            "jupyterlab_git": true
      }
    }
  }
```

The jupyter path can be e.g.:

[1] `~/.jupyter` => In this case, we create a `jupyterlab_git_server.json` (append `_server` to the name) at the same location.  
[2] `$CONDA_ENV/etc/jupyter/` =>  In this case, we create a `jupyterlab_git_server.json` (append `_server` to the name) at the same location.  
[3] `$CONDA_ENV/etc/jupyter/jupyter_notebook_config.d/` => In this case, we create a `jupyterlab_git.json` in `$CONDA_ENV/etc/jupyter/jupyter_server_config.d/`.  

@Zsailer I am not sure about the renaming of the file and storage at the same location. Do you see any other alternatives?

**End user experience***

The file collection will be achieved on each server start. If the collection is not empty, a warning message will be printed with the list of files to consider and a link to a documentation describing the next steps to take.

Those steps are:

- User can run a migration command `jupyter server notebook-extensions migrate` that will convert the collected files and write them at the correct location.
- The existing files remain untouched ensuring fallback in case of issue.
- User can run `jupyter server notebook-extensions undo-migration` that  will delete the migrated files (if any).
- Optional: `jupyter server notebook-extensions validate-migration` will load the migrated extensions via `load_server_extensions`.
- As the existing json files remain untouched, the warning message is still printed even after migration. It is the responsibility of the end-user to manually delete the existing json files.

**Comment by echarles** [comment]
@Zsailer @vidartf this is the place where we can discuss what needs to be done to ensure `nbclassic` provides the correct functionality to allow migration from `notebook` to `server` (see first comment of this issue)

**Comment by Zsailer** [comment]
I believe we solved the issues raised in this discussion by adding the shim layer in #7. Closing 🎉
